import { AbilityConstant, ConfigurationConstant, UIAbility, Want } from '@kit.AbilityKit';
import { hilog } from '@kit.PerformanceAnalysisKit';
import { window } from '@kit.ArkUI';
import { avSession } from '@kit.AVSessionKit';
import { AVSessionUtil } from '../utils/AVSessionUtil';
import { BusinessError } from '@kit.BasicServicesKit';

const DOMAIN = 0x0000;

export default class EntryAbility extends UIAbility {
  onCreate(want: Want, launchParam: AbilityConstant.LaunchParam): void {
    try {
      this.context.getApplicationContext().setColorMode(ConfigurationConstant.ColorMode.COLOR_MODE_NOT_SET);
    } catch (err) {
      hilog.error(DOMAIN, 'testTag', 'Failed to set colorMode. Cause: %{public}s', JSON.stringify(err));
    }
    hilog.info(DOMAIN, 'testTag', '%{public}s', 'Ability onCreate');
  }

  onDestroy(): void {
    hilog.info(DOMAIN, 'testTag', '%{public}s', 'Ability onDestroy');
  }

  onWindowStageCreate(windowStage: window.WindowStage): void {

    windowStage.loadContent('pages/Index', (err) => {
      if (err.code) {
        return;
      }
      this.createAVSession()
    });

    windowStage.getMainWindow().then((window)=>{
      let uiContext = window.getUIContext()
      let widthBreakpoint = uiContext.getWindowWidthBreakpoint()
      let heightBreakpoint = uiContext.getWindowHeightBreakpoint()
      AppStorage.setOrCreate("widthBreakpoint",widthBreakpoint)
      AppStorage.setOrCreate("heightBreakpoint",heightBreakpoint)
      window.on("windowSizeChange",()=>{
        let widthBreakpoint = uiContext.getWindowWidthBreakpoint()
        let heightBreakpoint = uiContext.getWindowHeightBreakpoint()
        AppStorage.setOrCreate("widthBreakpoint",widthBreakpoint)
        AppStorage.setOrCreate("heightBreakpoint",heightBreakpoint)
      })
    })

  }

  onWindowStageDestroy(): void {
    // Main window is destroyed, release UI related resources
    hilog.info(DOMAIN, 'testTag', '%{public}s', 'Ability onWindowStageDestroy');
  }

  onForeground(): void {
    // Ability has brought to foreground
    hilog.info(DOMAIN, 'testTag', '%{public}s', 'Ability onForeground');
  }

  onBackground(): void {
    // Ability has back to background
    hilog.info(DOMAIN, 'testTag', '%{public}s', 'Ability onBackground');
  }


  async createAVSession(){
    AVSessionUtil.session = await avSession.createAVSession(this.context,"mmmusic","audio")
    AVSessionUtil.setAVMetadate()
    AVSessionUtil.setAVPlayerState(avSession.PlaybackState.PLAYBACK_STATE_PAUSE)
    AVSessionUtil.setLanuchAbility()
    AVSessionUtil.onCtrlCommand()
      AVSessionUtil.session.activate()
        .then(()=>{
          console.log('系统窗口已激活')
        })
        .catch((err:BusinessError)=>{
          console.log('激活失败')
        })
  }
}